use glam::Vec2;
use iced::wgpu;
use iced::wgpu::util::DeviceExt;
use std::ops::Range;

/// Mesh data for a trace. The mesh only depends on the physical width of the chart widget,
/// therefore the mesh can be shared between multiple trace instances. This struct owns the vertex
/// and index buffers for the mesh, which are uploaded to the GPU and keeps track of the usage.
pub struct Mesh {
    vertex_buffer: wgpu::Buffer,
    index_buffer: wgpu::Buffer,
    index_count: u32,
    used: bool,
}

impl Mesh {
    const ATTRIBUTES: [wgpu::VertexAttribute; 1] = wgpu::vertex_attr_array![
        //position
        0 => Float32x2,
    ];

    pub fn create(device: &wgpu::Device, width: u32) -> Self {
        let vertices = trace_vertex_stripe(width);
        let vertex_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("TraceVertexBuffer"),
            contents: &bytemuck::cast_slice(vertices.as_slice()),
            usage: wgpu::BufferUsages::VERTEX,
        });

        let indices = trace_vertex_stripe_indices(width);
        let index_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("TraceIndexBuffer"),
            contents: &bytemuck::cast_slice(indices.as_slice()),
            usage: wgpu::BufferUsages::INDEX,
        });

        Self {
            vertex_buffer,
            index_buffer,
            index_count: indices.len() as u32,
            used: true,
        }
    }

    pub fn vertex_buffer_slice<'a>(&'a self) -> wgpu::BufferSlice<'a> {
        self.vertex_buffer.slice(..)
    }

    pub fn index_buffer_slice<'a>(&'a self) -> wgpu::BufferSlice<'a> {
        self.index_buffer.slice(..)
    }

    pub fn index_format(&self) -> wgpu::IndexFormat {
        wgpu::IndexFormat::Uint16
    }

    pub fn index_range(&self) -> Range<u32> {
        0..self.index_count
    }

    pub fn mark_used(&mut self) {
        self.used = true;
    }

    pub fn clear_usage(&mut self) {
        self.used = false;
    }

    pub fn is_used(&self) -> bool {
        self.used
    }

    pub fn desc<'a>() -> wgpu::VertexBufferLayout<'a> {
        wgpu::VertexBufferLayout {
            array_stride: std::mem::size_of::<Vec2>() as wgpu::BufferAddress,
            step_mode: wgpu::VertexStepMode::Vertex,
            attributes: &Self::ATTRIBUTES,
        }
    }
}

/// Generates the vertices for a triangle strip that forms a rectangle from (-1, -1) to (1, 1) with
/// `sample_count` samples along the x-axis.
///
/// The vertices are arrange in a zig-zag pattern as such:
///
/// ```text
/// 0---2---4
/// | / | / |
/// 1---3---5
/// ```
///
/// The shader projects these vertices from the normalized coordinates here to the time,
/// respectively physical domain, sampling the trace data and then projects them back to normalized
/// coordinates for rendering. Therefore the coordinates here are very straight forward and only
/// depend on the number of samples.
fn trace_vertex_stripe(sample_count: u32) -> Vec<Vec2> {
    debug_assert!(
        sample_count > 1,
        "Sample count must be greater than 1 to form valid triangles."
    );
    let vertex_count = sample_count * 2;
    let x_scale = 2.0 / (sample_count - 1) as f32;
    let mut vertices = Vec::with_capacity(vertex_count as usize);
    for i in 0..sample_count {
        let x = i as f32 * x_scale - 1.0;
        vertices.push(Vec2::new(x, 1.0));
        vertices.push(Vec2::new(x, -1.0));
    }
    vertices
}

/// Generates the indices for a triangle strip that connects the vertices generated by
/// `trace_vertex_stripe`.
///
/// The vertices are arrange in a zig-zag pattern as such:
///
/// ```text
/// 0---2---4
/// | / | / |
/// 1---3---5
/// ```
///
/// The indices need to form triangles like so:
///
/// ```text
/// 0---2           2
/// | /     +     / |
/// 1           1---3
/// ```
fn trace_vertex_stripe_indices(sample_count: u32) -> Vec<u16> {
    debug_assert!(
        sample_count > 1,
        "Sample count must be greater than 1 to form valid triangles."
    );
    debug_assert!(
        sample_count < 0x8000,
        "Sample count must be less than 32768 to fit in u16 indices."
    );
    let vertex_count = (sample_count - 1) * 6;
    let mut indices = Vec::with_capacity(vertex_count as usize);
    for i in 0..sample_count - 1 {
        let base = (i * 2) as u16;
        // First triangle
        indices.push(base);
        indices.push(base + 1);
        indices.push(base + 2);
        // Second triangle
        indices.push(base + 2);
        indices.push(base + 1);
        indices.push(base + 3);
    }
    indices
}

#[cfg(test)]
mod tests {
    use assert_float_eq::assert_f32_near;

    use super::*;

    #[test]
    fn trace_vertex_stripe_three_samples() {
        // Act
        let vertices = trace_vertex_stripe(3);

        // Assert
        assert_eq!(vertices.len(), 6);
        assert_f32_near!(vertices[0].x, -1.0);
        assert_f32_near!(vertices[5].x, 1.0);
    }

    #[test]
    fn trace_vertex_stripe_indices_three_samples() {
        // Act
        let indices = trace_vertex_stripe_indices(3);

        // Assert
        assert_eq!(
            indices.len(),
            12,
            "Expected 12 indices for 3 samples (2 triangles per sample, 3 indices per triangle)."
        );
        assert_eq!(
            indices,
            vec![
                0, 1, 2, // 1. Triangle
                2, 1, 3, // 2. Triangle
                2, 3, 4, // 3. Triangle
                4, 3, 5, // 4. Triangle
            ],
            "Expected indices to form two triangles for each sample."
        );
    }
}
