block-beta
    columns 3
    Toolbar s1["Window 1"] s2["Window 2"]
    block:scrollable:3
        columns 3
        l1["Legend 1"] p11["Plot 1"] p12["Plot 2"]
        l2["Legend 2"] p21["Plot 3"] p22["Plot 4"]
    end
    Footer:3
